sudo: false
dist: trusty

language: php

cache:
  directories:
    - $HOME/.composer/cache

matrix:
  include:
    - php: 7.2
      env: WP_VERSION=latest WP_TRAVISCI=phpcs
    - php: 7.1
      env: WP_VERSION=latest WP_TRAVISCI=phpcs
    - php: 7.0
      env: WP_VERSION=latest WP_TRAVISCI=phpcs

before_script:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - |
    if [ -f ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/xdebug.ini ]; then
      phpenv config-rm xdebug.ini
    else
      echo "xdebug.ini does not exist"
    fi
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      composer global require "phpunit/phpunit"
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      composer install
    fi

script:
  - |
    if [[ ! -z "$WP_VERSION" ]] ; then
      phpunit
      WP_MULTISITE=1 phpunit
      find . -name '*.php' ! -path "./vendor/*" ! -path "./wp-content/*" -print0 | xargs -0 -n 1 -P 4 php -l
    fi
  - |
    if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
      echo Running phpcs for PHP version $TRAVIS_PHP_VERSION …
      ./vendor/bin/phpcs --runtime-set testVersion $TRAVIS_PHP_VERSION
    fi

notifications:
  email: false
